gssd: ignore pipe directories that do not exist
Back when commit aba5ea5c and commit 55197c98
happen that replaced dnotify with inotify the
ignoring of non-existent upcall directories
got dropped. The patch adds it back and stops
following error log

ERROR: inotify_add_watch failed for nfs/clntXX:
No such file or directory

Signed-off-by: Steve Dickson <steved@redhat.com>